SELECT 
    VCODE,
    DTPERIOD,
    CONCAT(
        YEAR(DTPERIOD),
        '-Q',
        DATEPART(QUARTER, DTPERIOD)
    ) AS FiscalQuarter,
    PCTOCCUPIED,
    AVG(PCTOCCUPIED) OVER (
        PARTITION BY VCODE, YEAR(DTPERIOD)
        ORDER BY DTPERIOD
        ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
    ) AS YTDAvgPctOccupied,
    VVERSION
FROM ProjOccupancy
WHERE 
    delete_flag IS NULL
    AND VVERSION = 'Budget'
ORDER BY 
    VCODE,
    DTPERIOD;